name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Authenticate with GitHub
      run: echo "${{ secrets.GH_TOKEN }}" | npm login --registry=https://npm.pkg.github.com --scope=@thusarakap --stdin

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Publish
      run: npm publish